### ISSUE TITLE
[BUG] Intro Scene Dark

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Modset#110]
**I'm experiencing an issue with:**
- Script/Logic Error

**Describe the problem briefly**
When starting an operation during the night, the intro camera script will be quite dark if there's no adequate light source.

**Additional context**
ACE Mod uses a light source algorithm for their map lighting, we could utilise that to determine if NVGs are needed or not (with an override to disable NVG intro, if someone is making an atmospheric intro).

**Comment by Charlie-Bayne** [comment]
Could you give the "camera" night vision for the fullscreen, like the camera mode in Splendid camera?
