### ISSUE TITLE
[SUGGESTION] Modern Units Refactor

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Modset#124]
**Is your feature related to a problem? Please describe.**
 Currently the Modern Configs are dated and non-conforming with our standard approach.

**Describe the solution you'd like**
 I'd like to bring it in line with our modern configs, bringing the Units in-line with the correct macros and TWC custom config entries.

**Describe alternatives you've considered**
N/A

**Additional context**
Rik has started work on this already.

**Comment by Neciota** [comment]
#129 Dunzo.
