### ISSUE TITLE
[SUGGESTION] Flip Vehicles

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Modset#139]
**Is your feature related to a problem? Please describe.**
We have the bestest drivers. Sometimes they like the scenery, and want to get a real close look at it. The problem is, we can't return from being upside down easily.

**Describe the solution you'd like**
Add a flip option. This probably should be handled by some kind of recovery vehicle, or something (maybe the 3cb/ukcw repair vehicles). That simply rotates the vehicle correct way up. It should not repair them.

Ideally it'd be animated so it doesn't look utterly donkulous. Investigate utilising: https://community.bistudio.com/wiki/setVelocityTransformation 

Condition being the vehicle is empty of crew at the time.

**Describe alternatives you've considered**
A real basic method could be as follows:

```
_position = getPosATL _vehicle;
_vehicle setVectorUp surfaceNormal _position;
_vehicle setPosATL _position;
```

But this simple rights it immediately without any intermediate animation or movement.

**Additional context**
N/A

**Comment by Bosenator** [comment]
Debug scratch pad

```
[] spawn {
	_vehicle = cursorTarget;

	waitUntil {
		sleep 0.1;
		_vehicle setVectorUp ((vectorUp _vehicle) vectorAdd [0,0,0.1];
		((vectorUp surfaceNormal position _vehicle) vectorDiff (vectorUp _vehicle)) select 2 < 0.3
	};
};
```

**Comment by Hobbnob** [comment]
For situations where a recovery vehicle isn't available/feasible, might it be possible to allow a nearentities man check for getnumber armor to get a rough weight? That way a flip can be triggered if there's a lot of people standing next to it, and the amount of people required would depend on the 'weight' of the vehicle. Alternatively an ace interaction to put time of press into a variable on the vehicle, so that x amount of people need to choose to push within a certain timeframe.

**Comment by Bosenator** [comment]
I like the near-entities idea, would be good for landies. I'll add it.

**Comment by Bosenator** [comment]
Note: Add a Zeus module to do this, so it's a lot easier for the operator (without the proximity requirement). See additional comments for the Zeus code.

**Comment by Bosenator** [comment]
```
_object = cursorTarget;

TWC_flipVehicle = {
	params ["_object"];

	_startingTime = _object getVariable ["flipStartingTime", time];
	_endingTime = _object getVariable ["flipEndingTime", time];
	_interval = linearConversion [_startingTime, _endingTime, time, 0.010, 0.018];

	_object setVelocityTransformation [
		(_object getVariable ["flipStartingPos", (getposasl _object)]),
		(_object getVariable ["flipEndingPos", (getposasl _object)]),
		velocity _object,
		velocity _object,
		vectorDir _object,
		vectorDir _object,
		vectorUp _object,
		surfaceNormal position _object,
		_interval
	];

	if (_endingTime >= time) then { 
		[{ _this call TWC_flipVehicle; }, [_object]] call CBA_fnc_execNextFrame;
	};
};

_targetPosition = (getposasl _object);
_object setVariable ["flipStartingPos", _targetPosition, true];
_targetPosition set [2, ((ATLToASL (getposatl _object)) select 2)];
_object setVariable ["flipEndingPos", _targetPosition, true];

_startingTime = time;
_object setVariable ["flipStartingTime", _startingTime, true];
_endingTime = time + 10;
_object setVariable ["flipEndingTime", _endingTime, true];

[{ _this call TWC_flipVehicle; }, [_object]] call CBA_fnc_execNextFrame;
```

This is the current working scratch-pad. Two things encountered, the starting interval/ending interval will probably be different per vehicle (so I'll need to add a custom config value for supported vehicles). This was tested on a Land Rover, flipped on to its top. Secondly, I need to take the geometry bounding box into account; at the moment, it sort of just hovers in the end whilst turning, where as it should lower in altitude as it does so.
