### ISSUE TITLE
[BUG] AI Survive lethal hits

### ISSUE THREAD

**Issue by Hobbnob** [TheWreckingCrewUK/Modset#149]
**I'm experiencing an issue with:**
- Script/Logic Error

**Describe the problem briefly**
Shooting an AI in the head or chest with any non-explosive weapon still gives the chance for the unit to regain consciousness and fire back

**Additional context**
N/A

**Comment by Bosenator** [comment]
Can't do anything about chest, as that's just part of one selection: Torso. I think it's pretty fair to say there are Torso wounds that you can wake up from after being winded: ![Absolute Unit](https://4.bp.blogspot.com/-8TyiZqYO_w8/WijtXcn5usI/AAAAAAAAOpk/y2yBVXjmwJA1y2Wrt3QdceRosIK21QSpACLcBGAs/s1600/major_erik_bonde_1.jpg)

Will add blacklist to head selection recovery.

**Comment by Hobbnob** [comment]
Would a modifier for the chance to wake up be feasible? A torso shot should really have more chance of putting someone down than getting hit in the arm or leg, and I'd kinda expect a gutshot to be just as incapacitating in the short term as getting hit in the lung. This won't make much difference to long range engagements, but in room clearing where people put two in the chest by default I think there should be a realistic benefit to that as opposed to just spraying or nicking any feet or arms that are sticking out. As for the swedish soldier above I couldn't get much info apart from the bullet likely being from a musket of some description.

**Comment by McJazza** [comment]
I'm not qualified to say, but overhearing this convo I'm sat here thinking that really the problem is intwined with whatever way arma handles armour / plates (and to a probably non existent extent locality). Obvs a bullet to the plate is very different to no plate in these terms of injury severity. In hob's example a insurgent in a robe should sustain serious deadly injuries with two central chest hits, if he was a stalinium armoured ruski then less so... 

Not 100% sure what this adds to the convo but I think is a crucial consideration to make regarding the topic

**Comment by Hobbnob** [comment]
Thankfully that's a different issue, AI having armour on means they just don't go unconscious as easily. Reference all the times we hit someone in domi with 556 and see the tracer pinging off his helmet while he stays up

**Comment by Bosenator** [comment]
The way the "wake up" script works is that it bandages the AI on a random dice roll whilst they're unconscious every X seconds (random delay between checks). It doesn't do anything else. You may have noticed them having bandaged themselves before in their medical log, for example. Not all of them do regain consciousness. I've tried to keep the script as light as possible.

There is already a built in modifier for the initial damage caused to head and torso: https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_handleDamage.sqf#L118 - if the unit has received sufficient enough damage to cause either enough pain, a dent in their vitals, or bled out long enough, they won't regain consciousness, regardless of the bandaging.

As I have no way of inferring if the shot is in their lower abdomen or their chest, as the only selection is the entirety of their torso, and given that it already deals more damage, I'm happy enough for the expense of them being bandaged in their torso in FIBUA for the longer engagements overall.

As said previously, I will add a blacklist for the head selection, however.
