### ISSUE TITLE
[SUGGESTION] Medical Rewrite

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Modset#162]
**Is your feature related to a problem? Please describe.**
ACE 3 is currently amidst a rewrite of their medical system, of which we've significantly integrated and modified.

**Describe the solution you'd like**
This serves as a great chance to rewrite all the extensions I've written in the past, as the medical system has expanded beyond its original scope, with the clear direction laid ahead.

Will need to investigate into the possibility of porting existing systems over, that have become core, as well as potentially adding much wanted features from the past.

**CPR**
The foundation of our medical system is the evolution of the ACE 3 Revive System. We've mashed it into being an critical state system, which has worked well for us. However, in the rewrite they have decided to do away with that system altogether.

At a glance, it seems the rewrite has a critical system built into it, whereby performing CPR simulates a heart beat, and has a small chance to restart the heart altogether. If that's the case, then it may just be a case of altering these values to bring them more in-line with what we'd expect. This would do away with the calculations we perform based on blood level etc, as it would be included by its very nature.

- [x] Investigate new Revive System
- [x] If lacking, port Blood Loss effect
- [x] If lacking, port CPR chances (medic, epi, BL)
- [x] If lacking, add BL & BP upon successful resuscitation
- [x] Modify messages displayed in patient overview
- [ ] Port animation and its positional adjustment code
- [x] Port drowning (will need a new approach)

**Defib**
Should be fairly easy to port, as it's mostly separate. Good chance for a nice rewrite. Some functions etc. will need to be altered, if above speculations are proven. For example, no revive timer.

- [x] Port Defib code

**Suture Kit**
Open wounds don't seem to have been changed. Should be straight forward port. I'm very happy with the current code.

- [x] Port Suture Kit code

**Medication/Bandage Alterations**
I don't believe they've altered these configs, should be a straight port.

- [x] #379
- [x] Port Medication Times/Values

**(Field) Surgery**
Hasn't even been released yet, and it's broken as is. Porting it certainly won't hurt it.

- [ ] Port (Field) Surgery
- [ ] Port Surgical Masks
- [ ] Investigate Better UI for Remaining Gurneys

**Misc**
Misc changes that need to be ported.

- [x] Hide Blood Loss Warning
- [x] Hide Patient Overview
- [x] Port Bloodlust Insta-Kill code (and visibility check)
- [x] Port Tourniquet Timing Value
- [x] Port Self-Treatment Saline 250 ml
- [x] Port Uncon Sound Loop
- [x] Investigate need to port Vital Check Loop & force value sync
- [x] Port Debug to RPT

**Death Messages**
This system looks like it should be a lot easier to make, due to the new medical state machine. 

- [x] Rewrite the Death Reasoning logic, and hook into ACE medical far better than currently done

**AI**
- [ ] Port AI resuscitation system

**Curator/Editor**
- [x] Port Fully Bandage Unit
- [x] Port Resuscitate
- [x] Port Full Heal Without Log
- [x] Port Kill Unit
- [x] Port Inspect Unit
- [x] Port Log Unit
- [x] Port Medical Module (increases CPR chance on public)
- [x] Port Medical Facility Module (Field Tent)

**Describe alternatives you've considered**
Keeping the current system is entirely a possibility (and will be the case, until this is feature complete, if possible). Will need to branch ACE off to our own version for that, however.

**Additional context**
GOOD LUCK.

**Comment by Bosenator** [comment]
Updated post to reflect current branch. AI resuscitation will be pushed for a later release. I have marked some as 'completed' in cases where it won't be happening with the new system: for example, 'hide patient overview'. As those ports don't fit the critera as laid out in the forum post.

**Comment by Bosenator** [comment]
Additional things needed before launch: 
- [x] AI dispersion adjustment to decrease wound infliction rate, to off-set increased wound severity
- [ ] Investigate/implement proximity based AI skill decreasing, can be potential medium for keeping engaging fights at range w/o being stupidily OP in FIBUA

Things for post launch to investigate/implement:
- [ ] Ambulance specific changes to accomodate Defib decreased advantage - such as IV drip in vehicle, better burn treatment (more likely to encounter these in mechanised/motorised also, so ties in nicely), perhaps a speed increase on all treatments too
- [ ] Hand-off patient mechanic, that allows for in helicopters/ambulances for a patient to be perma-stable without interference - this will allow patients to be taken back without need for medic
- [ ] Replace PAK with working surgery system
- [ ] Investigate Fentanyl/Morphine/Pills gameplay loop

**Comment by Neciota** [comment]
Fall damage is reduced too much:
- [ ] Increase the damage from falling.

See [this](https://github.com/acemod/ACE3/blob/master/addons/medical_damage/ACE_Medical_Injuries.hpp#L63) comment on the ACE repository for information.
Also [this](https://github.com/acemod/ACE3/blob/73a7dbdc1ed90d3bbb41d453817263f99fc247b0/addons/medical_engine/functions/fnc_handleDamage.sqf#L134).

**Comment by Bosenator** [comment]
Falling damage seems to be armour dependent from testing, particularly surrounding a 90s smock. 

Using the following script:
```
_allVehicles = configFile >> "CfgVehicles";
_output = "";
_armour = [];

for "_i" from 0 to ((count _allVehicles) - 1) do {
	if (isClass (_allVehicles select _i)) then {
		_xClass = configName (_allVehicles select _i);
		
		if (_xClass != "") then {
			_titleArray = _xClass splitString "_";
			if (count _titleArray == 0) exitWith {};
			if (_titleArray select 0 != "TWC") exitWith {};
			if (getNumber ((_allVehicles select _i) >> "scope") != 2) exitWith {};
			if (!(_xClass isKindOf "CAManBase")) exitWith {};
			
			_uniformClass = getText ((_allVehicles select _i) >> "uniformClass");
			if !(_uniformClass in _armour) then {
				_armour pushBack _uniformClass;
				_armourValue = [(configFile >> "CfgVehicles" >> _xClass), "armor", -1] call BIS_fnc_returnConfigEntry;
				_armourSValue = [(configFile >> "CfgVehicles" >> _xClass), "armorStructural", -1] call BIS_fnc_returnConfigEntry;
				
				_allHitPoints = (configFile >> "CfgVehicles" >> _xClass >> "HitPoints");
				
				_hpOutput = endl;
				for "_j" from 0 to ((count _allHitPoints) - 1) do {
					_name = configName (_allHitPoints select _j);
					_arm = getNumber ((_allHitPoints select _j) >> "armor");
					_ace3armvalue = _armourValue * (1 max _arm);
					_hpOutput = _hpOutput + format ["// %1 - %2 ", _name, _ace3armvalue] + endl;
				};
				
				_string = format ["armour: %2 | armour structural: %3 | ace3 hitpoint armour values: %4 | classname: %1", _uniformClass, _armourValue, _armourSValue, _hpOutput];
				_output = _output + _string + " " + endl + endl;
			};
		};
	};
};

copyToClipboard _output;
```

Can't determine a value that sets it apart. However, the master branch in ACE3 has an unreleased reworking of the HandleDamage in Medical Engine, that does somewhat address this. We can either build that PBO ourselves in the interim until it's released, or hold off on releasing rewrite until such time. As it does change a lot of expected damage values as well, so it does seem counterproductive to do this work to only have to redo it in a few months time.
