### ISSUE TITLE
[SUGGESTION] AI Paradrop/Slingload in system.

### ISSUE THREAD

**Issue by Neciota** [TheWreckingCrewUK/Modset#171]
**Is your feature related to a problem? Please describe.**
Dismounted units are tricky to resupply in operations.

**Describe the solution you'd like**
An AI paradrop cargo module could be a nice flavourful way of supplying us. Possible helicopter slingload module?

**Describe alternatives you've considered**
We've given the platoon sergeant a vehicle to drive back and forth before, but it's not fantastic.

**Comment by Bosenator** [comment]
Already in, closed.

**Comment by Neciota** [comment]
I left this in because I wanted to make a module that spawned a heli which would slingload a box/vehicle to us.
