### ISSUE TITLE
[SUGGESTION] Checkable Vehicle ID's

### ISSUE THREAD

**Issue by Hobbnob** [TheWreckingCrewUK/Modset#172]
**Is your feature related to a problem? Please describe.**
We regularly have trouble telling different section's vehicles apart

**Describe the solution you'd like**
give the vehicles an ace interaction to set a variable on it, and another to check it. Only give the set ID capability to the high ranking people but let anyone check the ID. Maybe call it something less computerish. Having it as an ace option also puts it next to the cargo option where its relevant.

**Describe alternatives you've considered**
In the past we've used 3CB's numberplates and custom flag textures on tanks, but adding numberplates/paints to every vehicle we use would be a pain.

**Additional context**
N/A

**Comment by Hobbnob** [comment]
Looking back on this, it would be much easier to have an ace interaction on land vehicles for checking ID with no set ID function to avoid autism. When a player checks the ID, it looks at whether it's had one already and, if not, just create a random 2 digit variable and setvar broadcast the vehicle's ID from there. I'll put something together.

**Comment by Charlie-Bayne** [comment]
To emulate looking at something in the distance, would a system similar to
the nameplates be possible i.e press a button at it shows the vehicle id
above it. Obviously this should be tied to distance from the vehicle, and
possible reduced distance at night/ambient light level like the map?

**Comment by Hobbnob** [comment]
that would be absurdly impractical to produce

**Comment by Bosenator** [comment]
Which vehicle(s) is this necessary for? 3CB landies are already ID'd by number plate. Trucks shouldn't matter. Boats?

Seems unnecessary.

**Comment by Hobbnob** [comment]
WW2 is where we most commonly struggle, but we do also have the problem when dealing with boats as well as when an op uses indigenous military or civilian vehicles. It also helps when using RHS vehicles on the public server if differentiation is ever required there, but the biggest issues occur in ops.

**Comment by Bosenator** [comment]
OK, yeah WW2 is the issue. Boats & non-UK should't matter, as they don't have their inventories defined anyway.
