### ISSUE TITLE
[Side Mission] Convoy Loss

### ISSUE THREAD

**Issue by CrowJM64** [TheWreckingCrewUK/Modset#22]
A convoy was supposed to be travelling from X to Y, they have not arrived and now the players must find out what the issue is. Players arrive at a scene where the convoy is ambushed and when they get within X meters, the attack recommences and the Players come under attack from 2-3 sections of infantry. Maybe Truck must be taken to the Destination in order to complete the task, and if the truck is destroyed the task fails.
Looks like this: http://imgur.com/a/dzJHe

**Comment by Charlie-Bayne** [comment]
A technical would be great to add.

Also, is it possible to have a suspended state casualty at the scene? Would
add value to the mddic/mert. If you rescue the injured person, gain morale

**Comment by CrowJM64** [comment]
Well, they took out the Convoy so it wouldn't be a stretch to say they had a Technical.
