### ISSUE TITLE
[BUG] BLUFOR Units and the Air Assault Module

### ISSUE THREAD

**Issue by Mallas011** [TheWreckingCrewUK/Modset#223]
**I'm experiencing an issue with:**
- Incorrect Module Behaviour

**Describe the problem briefly**
When spawning BLUFOR Units in trough the Air Assault module, they somehow turn OPFOR or something, because regular BLUFOR units placed in the editor attack the newly spawned BLUFOR Air Assault unit spawned via the module.

**Additional context**
I tried this out with USMC by spawning a USMC CH53 loaded with a USMC Rifle Squad that was supposed to land on a USMC air field and drop of the units when a certain trigger condition was done. What happened is that as soon as the helicopter got close to the air field, the garrisoned USMC units started shooting at the helicopter.

**Comment by Bosenator** [comment]
Not a bug, is its intended behaviour. It was envisioned as an enemy air assault on to players module. Can be expanded to include friendly units.

**Comment by Neciota** [comment]
I recently adjusted this on the attack plane module too because it could cause airplanes to go wonky. Didn't bother adjusting it on this because I didn't foresee helicopters spawning in WW2. I'll adjust it though, good for ambiance.
