### ISSUE TITLE
[SUGGESTION] Save Gear on Disconnect

### ISSUE THREAD

**Issue by Bosenator** [TheWreckingCrewUK/Modset#233]
**Is your feature related to a problem? Please describe.**
When a player disconnects, due to technical fault or whatever the case maybe, their current loadout is lost and a fresh one is applied upon reconnecting. This has the problem of spawned in items being lost (perhaps a spawned in radio, or pair of binoculars because of wrong config). Additionally, if that unit was particuarly starved of ammo, that no longer matters as they'll be anew.

**Describe the solution you'd like**
When someone connects, and the mission has already started, then check if they're reconnecting. If they're reconnecting, to the same slot, then their loadout should be switched to their previous one.

We can do a very rudimentary check on their slot, by checking the classname of their role. Therefore if they were to switch roles (for whatever reason, perhaps accidentally connected to the wrong one), new gear would be loaded for them, as opposed to their old gear. 

**Describe alternatives you've considered**
N/A

**Additional context**
ACE has a feature like for respawning. We should look at how that's achieved, and apply it to reconnecting.

**Comment by Hobbnob** [comment]
If you check against typeof player as well this would be cool for public

**Comment by Charlie-Bayne** [comment]
One consideration, you need to save the state of earplugs or save that the
player has them in. If someone reconnects with this system, their earplugs
wont be "respawned" as they were not in their inventory
