### ISSUE TITLE
[SUGGESTION] Caching exemption module for zeus

### ISSUE THREAD

**Issue by Sargers** [TheWreckingCrewUK/Modset#255]
**Is your feature related to a problem? Please describe.**
Every now and again the caching system fucks up and keeps something cached which shouldnt be leading to a decreased amount of enemy in objectives and empty positions. There are also the occasional cases where something isnt exempted from caching accidentally where it should be (Operation REINDEER igla's) and this should be fixable in op.

**Describe the solution you'd like**
A Zeus module to put on group leaders that permanently unchaches a group of units.

**Describe alternatives you've considered**
A code snippet to run in the init fields of units?

**Additional context**
Potentially as a corollary to this can be a module to force caching (not forever but just the normal distance based caching) for performance reasons.

**Comment by Bosenator** [comment]
Closing as it was added at some point.

![](https://i.imgur.com/hMQcczC.png)
