### ISSUE TITLE
[SUGGESTION] Dynamic Stationary Unit cover usage

### ISSUE THREAD

**Issue by Sargers** [TheWreckingCrewUK/Modset#284]
**Is your feature related to a problem? Please describe.**
AI doesn't handle being behind cover very well and defaults to being prone for ages or you force them upright and they will brave God's own hail of gunfire without a care making them a turkey shoot for long range weapon systems such as tanks.

**Describe the solution you'd like**
Some sort of suppression check or whatever other method that makes the AI stand up more often to take shots but prones/hides behind cover when it receives a significant amount of gunfire. AKA Actual usage of its cover.

**Describe alternatives you've considered**
Force them to stand up straight and die.

**Comment by Hobbnob** [comment]
This is possible with a fired or a firednear eventhandler to check for each unit's suppression level, which would lower the unit if they're suppressed and raise them if not. A firednear eh would be more beneficial but I'm not sure how much extra performance that would hit in trench situations

**Comment by rwalker959** [comment]
Implemented (Sort of) with https://github.com/TheWreckingCrewUK/Modset/pull/392
