### ISSUE TITLE
[BUG] 2 inch deleting ammo from user

### ISSUE THREAD

**Issue by Sargers** [TheWreckingCrewUK/Modset#292]
**I'm experiencing an issue with:**
- Script/Logic Error

**Describe the problem briefly**
The 2 inch is apparently eating ammo from the mortarman whenever they try to use the 2 inch. It takes roughly half each time causing massive ammo issues and making the 2 inch effectively unusable.

**Additional context**
Grusey experienced this in Op FIREFORCE.

**Comment by Neciota** [comment]
Lets just assume the troubling amount of repo pushes have fixed the issue.
