### ISSUE TITLE
[SUGGESTION] Master Box

### ISSUE THREAD

**Issue by Neciota** [TheWreckingCrewUK/Modset#297]
**Is your feature related to a problem? Please describe.**
Boxes are objects. Objects lag the game. Limit objects.

**Describe the solution you'd like**
A master box to rule (and fill) all other boxes back to their default, much like the ACE3 vehicle ammo boxes.  

**Describe alternatives you've considered**
Bigger boxes.

**Additional context**
N/a.

**Comment by Neciota** [comment]
Also Bose's inferior task that I totally knew was there #273

**Comment by Bosenator** [comment]
Closing as related to #273
