### ISSUE TITLE
#45 - Actual Correct Unit Stuff

### ISSUE THREAD

**Issue by CrowJM64** [TheWreckingCrewUK/Modset#31]
Changelog:

Added:
Machine Gunner Loadout
Asst. Machine Gunner Loadout

Changed:
All Infantry are all called "Charlie XXXX"
USMC Jet Pilot spawned with different backpack to the respawned one, changed to "rhsusf_falconii"

Removed:
Removed all (Modern) tags from description names.

Additionally:
Higher ranks such as Platoon commander and Sniper/Spotter were left without Charlie tag ass they do not currently have them in Public.

LOADOUTS:
class Modern_USMC_Base: B_Soldier_base_F
{
scope=1;
displayName="Base (Modern)";
faction="twc_faction";
editorSubcategory = "Men_Modern";
vehicleClass="Men_Modern";
icon="iconMan";
nakedUniform="U_BasicBody";
uniformClass="rhs_uniform_FROG01_d";
linkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
Items[]=
{
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_quikclot",
"ACE_quikclot",
"ACE_morphine",
"ACE_epinephrine",
"ACE_tourniquet",
"ACE_tourniquet",
"ACRE_PRC148",
"ACE_MapTools",
"ACE_EarPlugs"
};
respawntems[]=
{
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_fieldDressing",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_elasticBandage",
"ACE_quikclot",
"ACE_quikclot",
"ACE_morphine",
"ACE_epinephrine",
"ACE_tourniquet",
"ACE_tourniquet",
"ACRE_PRC148",
"ACE_EarPlugs"
};
};
class Modern_USMC_Squadleader: Modern_USMC_Base
{
scope=2;
displayName="Charlie Squad Leader";
icon="iconManLeader";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m16a4_carryhandle_pmag",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m16a4_carryhandle_pmag",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_Teamleader: Modern_USMC_Base
{
scope=2;
displayName="Charlie Team Leader";
icon="iconManLeader";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m16a4_carryhandle_pmag",
"rhsusf_weap_m9",
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m16a4_carryhandle_pmag",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_Rifleman: Modern_USMC_Base
{
scope=2;
displayName="Charlie Rifleman";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m16a4_carryhandle_grip",
"rhs_weap_M136_hedp",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m16a4_carryhandle_grip",
"rhs_weap_M136_hedp",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_Autorifleman: Modern_USMC_Base
{
scope=2;
displayName="Charlie Autorifleman";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_mg",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m249_pip_L",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m249_pip_L",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_AsstAutorifleman: Modern_USMC_Base
{
scope=2;
displayName="Charlie Asst. Automatic Rifleman";
icon="iconManMG";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_grip",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_grip",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_MachineGunner: Modern_USMC_Base
{
scope=2;
displayName="Charlie Machine Gunner";
icon="iconManMG";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_mg",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_mg",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m240b",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m240b",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_100Rnd_762x51",
"rhsusf_100Rnd_762x51",
"rhsusf_100Rnd_762x51_m62_tracer",
"rhsusf_100Rnd_762x51_m62_tracer",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_100Rnd_762x51",
"rhsusf_100Rnd_762x51",
"rhsusf_100Rnd_762x51_m62_tracer",
"rhsusf_100Rnd_762x51_m62_tracer",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_AsstMachineGunner: Modern_USMC_Base
{
scope=2;
displayName="Charlie Asst. Machine Gunner";
icon="iconManMG";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_rifleman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_grip",
"rhs_weap_M136_hedp",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_grip",
"rhs_weap_M136_hedp",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_Medic: Modern_USMC_Base
{
scope=2;
displayName="Charlie Medic";
icon="iconManMedic";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_corpsman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_corpsman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_grip",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_grip",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"CUP_HandGrenade_L109A2_HE",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
class EventHandlers: EventHandlers
{
init = "init = if(local (_this select 0))then{(_this select 0) setVariable [""ace_medical_medicClass"",1]};";
};
};
class Modern_USMC_Platoon_Commander: Modern_USMC_Squadleader
{
scope=2;
displayName="USMC Platoon Commander";
backpack="rhsusf_assault_eagleaiii_coy";
icon="iconManLeader";
linkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_squadleader",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
};
class Modern_USMC_Platoon_Sergeant: Modern_USMC_Platoon_Commander
{
scope=2;
displayName="USMC Platoon Commander";
backpack="rhsusf_assault_eagleaiii_coy";
icon="iconManLeader";
linkedItems[]=
{
"rhsusf_spc_squadleader",
"rhs_uniform_FROG01_d",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
respawnLinkedItems[]=
{
"rhsusf_spc_squadleader",
"rhs_uniform_FROG01_d",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch",
"UK3CB_BAF_G_Tactical_Black"
};
};
class Modern_USMC_HeliPilot: Modern_USMC_Base
{
scope=2;
displayName="USMC Helicopter Pilot";
uniformClass="CUP_U_B_USArmy_PilotOverall";
backpack="rhsusf_falconii_coy";
linkedItems[]=
{
"CUP_H_USMC_Helmet_Pilot",
"CUP_V_B_PilotVest",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ACE_microDAGR_Item"
};
respawnLinkedItems[]=
{
"CUP_H_USMC_Helmet_Pilot",
"CUP_V_B_PilotVest",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ACE_microDAGR_Item"
};
weapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m9",
"rhs_weap_m4"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m9",
"rhs_weap_m4"
};
magazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_JetPilot: Modern_USMC_Base
{
_generalMacro="Modern_USMCJetPilot";
scope=2;
displayName="USMC Jet Pilot";
faction="twc_faction";
editorSubcategory = "Men_Modern";
vehicleClass="Men_Modern";
icon="iconMan";
nakedUniform="U_BasicBody";
uniformClass="CUP_U_B_USMC_PilotOverall";
backpack="rhsusf_falconii";
linkedItems[]=
{
"RHS_jetpilot_usaf",
"rhsusf_falconii",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ACE_microDAGR_Item"
};
respawnLinkedItems[]=
{
"RHS_jetpilot_usaf",
"rhsusf_falconii",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ACE_microDAGR_Item"
};
weapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m9"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhsusf_weap_m9"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_MortarGunner: Modern_USMC_Rifleman
{
scope=2;
displayName="USMC Mortar Gunner";
icon="iconMan";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_corpsman",
"UK3CB_BAF_H_Mk7_Camo_D",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_corpsman",
"UK3CB_BAF_H_Mk7_Camo_D",
"ItemMap",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_pmag",
"UK3CB_BAF_L16"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_pmag",
"UK3CB_BAF_L16"
};
magazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"rhs_mag_30Rnd_556x45_Mk318_Stanag",
"SmokeShell"
};
};
class Modern_USMC_MortarAssistant: Modern_USMC_MortarGunner
{
displayName="USMC Mortar Assistant";
backpack="rhsusf_assault_eagleaiii_coy";
weapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_pmag",
"UK3CB_BAF_L16_Tripod"
};
respawnweapons[]=
{
"Throw",
"Put",
"rhs_weap_m16a4_carryhandle_pmag",
"UK3CB_BAF_L16_Tripod"
};
};
class Modern_USMC_Sniper: Modern_USMC_Base
{
scope=2;
displayName="USMC Sniper";
nakedUniform="U_BasicBody";
uniformClass="rhs_uniform_FROG01_d";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_light",
"rhsusf_mich_helmet_marpatd_norotos_headset",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_light",
"rhsusf_mich_helmet_marpatd_norotos_headset",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m40a5_d"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhsusf_weap_m9",
"rhs_weap_m40a5_d"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"rhsusf_10Rnd_762x51_m118_special_Mag",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_Spotter: Modern_USMC_Sniper
{
displayName="USMC Spotter";
icon="iconManLeader";
nakedUniform="U_BasicBody";
uniformClass="rhs_uniform_FROG01_d";
backpack="rhsusf_assault_eagleaiii_coy";
weapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m4_carryhandle_pmag"
};
respawnweapons[]=
{
"Throw",
"Put",
"ACE_Vector",
"rhs_weap_m4_carryhandle_pmag"
};
magazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
Respawnmagazines[]=
{
"rhsusf_mag_15Rnd_9x19_JHP",
"rhsusf_mag_15Rnd_9x19_JHP",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"30Rnd_556x45_Stanag",
"CUP_HandGrenade_L109A2_HE",
"SmokeShell",
"SmokeShell",
"SmokeShell"
};
};
class Modern_USMC_FAC: Modern_USMC_Base
{
scope=2;
displayName="USMC FAC";
backpack="rhsusf_assault_eagleaiii_coy";
linkedItems[]=
{
"rhsusf_spc_crewman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
respawnLinkedItems[]=
{
"rhsusf_spc_crewman",
"rhsusf_mich_helmet_marpatd",
"ItemMap",
"ItemcTab",
"ItemCompass",
"ItemWatch"
};
weapons[]=
{
"Throw",
"Put",
"UK3CB_BAF_Soflam_Laserdesignator",
"rhs_weap_m4_carryhandle_pmag"
};
respawnweapons[]=
{
"Throw",
"Put",
"UK3CB_BAF_Soflam_Laserdesignator",
"rhs_weap_m4_carryhandle_pmag"
};
magazines[]=
{
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red"
};
Respawnmagazines[]=
{
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red",
"30Rnd_556x45_Stanag_Tracer_Red"
};
};

**Comment by jayman9696** [comment]
closed in last update. i got my numbers wrong
