### ISSUE TITLE
[BUG] Profiler Mastertask

### ISSUE THREAD

**Issue by Neciota** [TheWreckingCrewUK/Modset#311]
**I'm experiencing an issue with:**
Performance can be _better_.

**Describe the problem briefly**
Observations from DUNSTALL:
- TWC_fnc_gunwalk executed hundreds of times locally to the client in an operation despite meant as an AI adjustment. Why does it run locally?
- TWC_fnc_init executed 267 times. ~~What is it initializing?~~ This initializes AI. It is called on CAManBase init, why 267 times? It should only run once, on client init. Implies client was initialized 267 times, or 266 AI were initialized on client.
- ~~TWC_Core_fnc_initNightGear executed 267 times. We did not even get any night gear.~~
- TWC_disposable_fnc_addDisposableHandler executed 11,766 times. While mean execution time was low, it might not be necessary.
- TWC_fnc_confiscateBadItems executed 267 times. Does this run for AI or us? Investigate.
- ~~TWC_2inch_fnc_deploy executed 18 times in an operation with no 2inch.~~ Executes when you press 3, onkeyHandler.
- TWC_2inch_fnc_ui executed 4 times in an operation with no 2inch.
- TWC_2inch_fnc_init executed 2 times in an operation with no 2inch.

**Additional context**
N/a.

**Comment by Bosenator** [comment]
Updated to reflect changes done in https://github.com/TheWreckingCrewUK/Modset/commit/9dfb275540f02ffd67512dfc5bcea81136832bb5 regarding nightgear init being called too much.

**Comment by Bosenator** [comment]
> TWC_fnc_init executed 267 times. What is it initializing? This initializes AI. It is called on CAManBase init, why 267 times? It should only run once, on client init. Implies client was initialized 267 times, or 266 AI were initialized on client.

It's running for each init per soldier in the mission. This will run for each AI unit on each client, even if the unit isn't local. There's a local check inside for this reason. This cannot be confined to serverInit per headless client requiring it, unfortunately. One alternative is a postInit script variant, that'll check locality first and then execute inits. Performance wise it's negligible. 

Same applies for confiscate, which is intended to run on AI.
