### ISSUE TITLE
[SUGGESTION] Flare Module

### ISSUE THREAD

**Issue by SaxonPhoenix** [TheWreckingCrewUK/Modset#318]
**Is your feature related to a problem? Please describe.**
AI units are notoriously bad at night combat. They (and in certain eras even we) need flares to fight properly. What we need is a simple way to have (respawning) flares over an area.

**Describe the solution you'd like**
A module that keeps spawning flares at a set / semi-random interval as long as a condition is met. Along the lines of this script: https://pastebin.com/NMpkRvNX (from this thread https://www.reddit.com/r/armadev/comments/393f15/creating_repeat_sky_flares/).

**Describe alternatives you've considered**
Using flares from the Artillery module, though those will easily run out to early / keep firing.

**Comment by Bosenator** [comment]
There's a vanilla module for flares in-game, IIRC.
