### ISSUE TITLE
Improved stamina for Airbourne/Amphibious

### ISSUE THREAD

**Issue by Charlie-Bayne** [TheWreckingCrewUK/Modset#36]
Given that in these force types we play as "Elite" infantry (Marines/Para's) and that we are carrying more and exclusively walking, can we adjust the stamina settings so that the individuals recover faster and have a larger health "pool" 

Not a huge amount, say 20% extra

**Comment by jayman9696** [comment]
Yea, We won't edited base arma 3 values. The trick is to lower weight by dropping unnecessary gear like maptools

**Comment by Charlie-Bayne** [comment]
Added invalid tag due to management Map tool based prejudices
