### ISSUE TITLE
Player Disconnect Issue, Ops Server

### ISSUE THREAD

**Issue by Neciota** [TheWreckingCrewUK/Modset#72]
`20:14:43 Error in expression <Variable ["disconnectedPlayerUID", -1]) == _uid) then {
deleteVehicle _x;
};
} f>`

Server has this error in the log. [Related file.](https://github.com/TheWreckingCrewUK/Modset/blob/cdee600e60378aac16a0bb80623175c789c0488e/%40twc_framework/addons/twc_framework/modules/fn_disconnectGear.sqf)

**Comment by Bosenator** [comment]
Yeah, we know. BI related issue, not our end.
